#!/usr/bin/perl
#
# for nginx, copycat of htpasswd from apache

use strict;

if (@ARGV != 2) {
    print "Usage: $0 login password\n";
    exit 1;
} else {
    chomp(my $login=$ARGV[0]);
    chomp(my $password=$ARGV[1]);
    print $login.":".crypt($password,$login)."\n";
}
